CREATE DATABASE COMPANY_XYZ;
USE COMPANY_XYZ;

CREATE TABLE EMPLOYE_INFO(
  ID INT PRIMARY KEY,
  NAME VARCHAR (100),
  SALARY INT 
);

INSERT INTO EMPLOYE_INFO
(ID, NAME, SALARY)
VALUES
(1, "MAHESH", 30000),
(2, "SANTOSH", 25000),
(3, 'MANOJ' , 36000);

INSERT INTO EMPLOYE_INFO VALUES (4, 'CHOTU' , 40000);

SELECT * FROM EMPLOYE_INFO;